name: Release
on:
  workflow_run:
    workflows: [ Sync with upstream ]
    types: [ completed ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly

# Build on the oldest supported images, so we have broader compatibility
# Build with gcc-10 to prevent triggering #14150 (default is still gcc-9 on 20.04)
jobs:
  linux:
    runs-on: ubuntu-18.04
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    outputs:
      version: ${{ steps.build.outputs.version }}
      release: ${{ steps.build.outputs.release }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake gettext libtool-bin locales ninja-build pkg-config unzip
      - if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly'
        run: printf 'NVIM_BUILD_TYPE=Release\n' >> $GITHUB_ENV
      - if: github.event_name == 'workflow_run' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name == 'nightly')
        run: printf 'NVIM_BUILD_TYPE=RelWithDebInfo\n' >> $GITHUB_ENV
      - if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly'
        name: Check out selected revision (tag)
        run: git checkout tags/${{ github.event.inputs.tag_name }}
      - if: github.event_name == 'workflow_run' || github.event.inputs.tag_name == 'nightly'
        name: Check out first parent (upstream HEAD)
        run: git reset --hard HEAD^
      - name: Build release
        id: build
        run: |
          CC=gcc-10 make CMAKE_BUILD_TYPE=${NVIM_BUILD_TYPE} CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH="
          printf '::set-output name=version::%s\n' "$(./build/bin/nvim --version | head -n 3 | sed -z 's/\n/%0A/g')"
          printf '::set-output name=release::%s\n' "$(./build/bin/nvim --version | head -n 1)"
          make DESTDIR="$GITHUB_WORKSPACE/build/release/nvim-linux64" install
          cd "$GITHUB_WORKSPACE/build/"
          cpack -C $NVIM_BUILD_TYPE
      - uses: actions/upload-artifact@v3
        with:
          name: nvim-linux64
          path: |
            build/nvim-linux64.tar.gz
            build/nvim-linux64.deb
          retention-days: 1

  appimage:
    runs-on: ubuntu-18.04
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake gettext libtool-bin locales ninja-build pkg-config unzip
      - if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly'
        name: Check out selected revision (tag)
        run: git checkout tags/${{ github.event.inputs.tag_name }}
      - if: github.event_name == 'workflow_run' || github.event.inputs.tag_name == 'nightly'
        name: Check out first parent (upstream HEAD)
        run: git reset --hard HEAD^
      - if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly'
        run: CC=gcc-10 make appimage-latest
      - if: github.event_name == 'workflow_run' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name == 'nightly')
        run: CC=gcc-10 make appimage-nightly
      - uses: actions/upload-artifact@v3
        with:
          name: appimage
          path: |
            build/bin/nvim.appimage
            build/bin/nvim.appimage.zsync
          retention-days: 1

  publish:
    needs: [linux, appimage]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      # Must perform checkout first, since it deletes the target directory
      # before running, and would therefore delete the downloaded artifacts
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gettext-base

      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
      - if: github.event_name == 'workflow_run'
        run: echo 'TAG_NAME=nightly' >> $GITHUB_ENV
      - if: env.TAG_NAME == 'nightly'
        run: |
          (echo 'SUBJECT=Nvim development (prerelease) build';
           echo 'PRERELEASE=--prerelease') >> $GITHUB_ENV
          gh release delete nightly --yes || true
          git push origin :nightly || true
      - if: env.TAG_NAME != 'nightly'
        run: |
          (echo 'SUBJECT=Nvim release build';
           echo 'PRERELEASE=') >> $GITHUB_ENV
      # `sha256sum` outputs <sha> <path>, so we cd into each dir to drop the
      # containing folder from the output.
      - name: Generate Linux64 SHA256 checksums
        run: |
          cd ./nvim-linux64
          sha256sum nvim-linux64.tar.gz > nvim-linux64.tar.gz.sha256sum
          echo "SHA_LINUX_64_TAR=$(cat nvim-linux64.tar.gz.sha256sum)" >> $GITHUB_ENV
          sha256sum nvim-linux64.deb > nvim-linux64.deb.sha256sum
          echo "SHA_LINUX_64_DEB=$(cat nvim-linux64.deb.sha256sum)" >> $GITHUB_ENV
      - name: Generate App Image SHA256 checksums
        run: |
          cd ./appimage
          sha256sum nvim.appimage > nvim.appimage.sha256sum
          echo "SHA_APP_IMAGE=$(cat nvim.appimage.sha256sum)" >> $GITHUB_ENV
      - name: Generate App Image Zsync SHA256 checksums
        run: |
          cd ./appimage
          sha256sum nvim.appimage.zsync > nvim.appimage.zsync.sha256sum
          echo "SHA_APP_IMAGE_ZSYNC=$(cat nvim.appimage.zsync.sha256sum)" >> $GITHUB_ENV
      - if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly'
        name: Check out selected revision (tag)
        run: git checkout tags/${{ github.event.inputs.tag_name }}
      - if: github.event_name == 'workflow_run' || github.event.inputs.tag_name == 'nightly'
        name: Check out first parent (upstream HEAD)
        run: git reset --hard HEAD^
      - name: Set current revision (commit SHA)
        id: rev
        run: echo "::set-output name=sha::$(git rev-parse --verify 'HEAD^{commit}')"
      - name: Publish release
        env:
          NVIM_VERSION: ${{ needs.linux.outputs.version }}
          DEBUG: api
        run: |
          git checkout $GITHUB_SHA -- .github/workflows/notes.md
          envsubst < "$GITHUB_WORKSPACE/.github/workflows/notes.md" > "$RUNNER_TEMP/notes.md"
          gh release create $TAG_NAME $PRERELEASE --notes-file "$RUNNER_TEMP/notes.md" --title "$SUBJECT" --target ${{ steps.rev.outputs.sha }} nvim-linux64/* appimage/*
