name: Sync with upstream
on:
  schedule:
    - cron: '5 5 * * *'
  workflow_dispatch: {}

jobs:
  rebase-sync:
    runs-on: ubuntu-latest
    steps:

      - name: Impersonate update bot
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/neovim/neovim.git
          git fetch upstream --no-tags

      - name: Rebase onto upstream
        run: |
          git config user.name "antoineco"
          git config user.email "antoineco@users.noreply.github.com"
          git rebase upstream/master

      - name: Push changes
        run: git push --force
